name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repo using git
        uses: actions/checkout@v4
      
      - name: Install, build, and upload your site to GitHub Pages
        uses: withastro/action@v2
        with:
          path: ./
          node-version: 18
          package-manager: npm 